export type ReviewGrade = 'AGAIN' | 'HARD' | 'GOOD' | 'EASY';
export interface SrsState { repetitions: number; intervalDays: number; easeFactor: number; correctCount: number; wrongCount: number; lastReviewedAt?: number; nextReviewAt: number; strength: number; }
export const INITIAL_EASE_FACTOR = 2.5; export const MIN_EASE_FACTOR = 1.3; export const MAX_EASE_FACTOR = 2.8; export const AGAIN_DELAY_MS = 10 * 60 * 1000;
const DAY_MS = 24 * 60 * 60 * 1000;
const number = (value: unknown, fallback: number) => typeof value === 'number' && Number.isFinite(value) ? value : fallback;
export const toMillis = (value: unknown) => value && typeof (value as { toMillis?: unknown }).toMillis === 'function' ? (value as { toMillis: () => number }).toMillis() : value instanceof Date ? value.getTime() : number(value, 0);
export const strengthFromSrs = (state: Pick<SrsState, 'repetitions' | 'intervalDays' | 'correctCount' | 'wrongCount'>) => state.repetitions <= 0 || state.wrongCount > state.correctCount ? 1 : state.intervalDays <= 1 ? 2 : state.intervalDays <= 7 ? 3 : state.intervalDays <= 30 ? 4 : 5;
export const initialSrsState = (value: Record<string, unknown> = {}): SrsState => { const state = { repetitions: Math.max(0, number(value.repetitions, 0)), intervalDays: Math.max(0, number(value.intervalDays, 0)), easeFactor: Math.max(MIN_EASE_FACTOR, Math.min(MAX_EASE_FACTOR, number(value.easeFactor, INITIAL_EASE_FACTOR))), correctCount: Math.max(0, number(value.correctCount, 0)), wrongCount: Math.max(0, number(value.wrongCount, 0)), lastReviewedAt: value.lastReviewedAt === undefined ? undefined : toMillis(value.lastReviewedAt), nextReviewAt: value.nextReviewAt === undefined ? toMillis(value.nextReviewDate) : toMillis(value.nextReviewAt), strength: 1 }; return { ...state, strength: strengthFromSrs(state) }; };
export const calculateNextReview = (value: Record<string, unknown>, grade: ReviewGrade, reviewedAt: number): SrsState => { const base = initialSrsState(value); let repetitions = base.repetitions, intervalDays = base.intervalDays, easeFactor = base.easeFactor, correctCount = base.correctCount, wrongCount = base.wrongCount, nextReviewAt: number; switch (grade) { case 'AGAIN': repetitions = 0; intervalDays = 0; easeFactor = Math.max(MIN_EASE_FACTOR, easeFactor - .2); wrongCount++; nextReviewAt = reviewedAt + AGAIN_DELAY_MS; break; case 'HARD': repetitions++; intervalDays = Math.max(1, Math.round((intervalDays || 1) * 1.2)); easeFactor = Math.max(MIN_EASE_FACTOR, easeFactor - .15); correctCount++; nextReviewAt = reviewedAt + intervalDays * DAY_MS; break; case 'GOOD': repetitions++; intervalDays = base.repetitions === 0 ? 1 : base.repetitions === 1 ? 3 : Math.max(1, Math.round(intervalDays * easeFactor)); correctCount++; nextReviewAt = reviewedAt + intervalDays * DAY_MS; break; case 'EASY': repetitions++; intervalDays = base.repetitions === 0 ? 4 : Math.max(1, Math.round((intervalDays || 1) * easeFactor * 1.3)); easeFactor = Math.min(MAX_EASE_FACTOR, easeFactor + .15); correctCount++; nextReviewAt = reviewedAt + intervalDays * DAY_MS; break; } const result = { repetitions, intervalDays, easeFactor, correctCount, wrongCount, lastReviewedAt: reviewedAt, nextReviewAt, strength: 1 }; return { ...result, strength: strengthFromSrs(result) }; };
