// @vitest-environment jsdom
import React from 'react';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const tts = vi.hoisted(() => ({ speaking: false, synchronizationSupported: true, activeTokenIndex: undefined as number | undefined, activeSentenceId: undefined as string | undefined, pause: vi.fn(), stop: vi.fn(), useReaderTts: vi.fn() }));
vi.mock('../hooks/useReaderTts', () => ({ useReaderTts: tts.useReaderTts }));
vi.mock('../services/readerLanguageData', () => ({ LatestTapGuard: class { private request = 0; next() { return ++this.request; } isLatest(request: number) { return request === this.request; } }, readerLanguageData: { loadChapter: vi.fn(async () => ({ mode: 'prepared', metadata: { chapterContentHash: 'h', processingVersion: '1', sourceLanguage: 'en', targetLanguage: 'tr', tokenChunkSize: 50 }, tokens: [{ index: 0, text: 'Door', normalized: 'door', start: 0, end: 4, sentenceId: 's1', isWord: true }, { index: 1, text: ' ', normalized: null, start: 4, end: 5, sentenceId: 's1', isWord: false }, { index: 2, text: 'door', normalized: 'door', start: 5, end: 9, sentenceId: 's1', isWord: true }], dictionaries: new Map(), dictionaryPrefetch: Promise.resolve() })), resolve: vi.fn(async () => ({ state: 'missing' })) } }));
import BookReaderV2 from '../components/BookReaderV2';

const book: any = { id: 'b', title: 'B', author: 'A', level: 'A1', coverUrl: '', excerpt: '', totalWords: 2, requiredPlan: [], archived: false, languageProcessingStatus: 'COMPLETED', chapters: [{ id: 'c1', title: 'C1', content: 'Door door' }, { id: 'c2', title: 'C2', content: 'Next' }] };
const renderReader = () => render(<BookReaderV2 book={book} initialChapterIndex={0} onBack={vi.fn()} onSaveWord={vi.fn()} savedWords={[]} onCompleteChapter={vi.fn()} onUpdateProgress={vi.fn()} />);
describe('BookReader TTS integration', () => { beforeEach(() => { tts.speaking = false; tts.activeTokenIndex = undefined; tts.activeSentenceId = undefined; tts.pause.mockClear(); tts.stop.mockClear(); tts.useReaderTts.mockClear(); tts.useReaderTts.mockImplementation(() => ({ supported: true, status: 'IDLE', paused: false, rate: 1, voice: undefined, voices: [], setVoice: vi.fn(), followEnabled: true, setFollowEnabled: vi.fn(), start: vi.fn(), startFromToken: vi.fn(), resume: vi.fn(), setRate: vi.fn(), repeatCurrentSentence: vi.fn(), previousSentence: vi.fn(), nextSentence: vi.fn(), speaking: tts.speaking, synchronizationSupported: tts.synchronizationSupported, activeTokenIndex: tts.activeTokenIndex, activeSentenceId: tts.activeSentenceId, pause: tts.pause, stop: tts.stop })); }); afterEach(cleanup); it('opens silently and preserves repeated chapter words', async () => { renderReader(); expect(await screen.findByRole('button', { name: 'Door çevirisini göster' })).toBeTruthy(); expect(screen.getAllByRole('button', { name: 'door çevirisini göster' })).toHaveLength(1); }); it('pauses narration before the existing translation selection flow', async () => { tts.speaking = true; renderReader(); expect(tts.useReaderTts).toHaveBeenCalled(); const results = tts.useReaderTts.mock.results; expect(results[results.length - 1]?.value.speaking).toBe(true); fireEvent.click(await screen.findByRole('button', { name: 'door çevirisini göster' })); await waitFor(() => expect(tts.pause).toHaveBeenCalledTimes(1)); expect(screen.getByText('Hazırlanmış çeviri verisi kullanılamıyor.')).toBeTruthy(); }); });
