import assert from 'node:assert/strict';
import { after, before, beforeEach, test } from 'node:test';
import { initializeTestEnvironment } from '@firebase/rules-unit-testing';
const projectId='demo-readlex-tests', host='127.0.0.1', port=8080; process.env.FIRESTORE_EMULATOR_HOST=`${host}:${port}`; process.env.GCLOUD_PROJECT=projectId;
const { adminDb } = await import('../functions/lib/admin.js'); const { getEntitlements, startTrial, assignManualSubscription, DEFAULT_TRIAL_DAYS } = await import('../functions/lib/subscriptions/service.js');
let env; before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host,port}})}); beforeEach(async()=>env.clearFirestore()); after(async()=>env.cleanup());
test('new account resolves free and server starts one idempotent three-day trial', async()=>{ assert.equal((await getEntitlements('alice',100)).effectivePlan,'FREE'); const first=await startTrial('alice',100); const second=await startTrial('alice',200); const saved=(await adminDb.doc('subscriptions/alice').get()).data(); assert.equal(first.status,'TRIALING'); assert.equal(first.isPremium,true); assert.deepEqual(second,first); assert.equal(saved.trialUsedAt,100); assert.equal(saved.trialEndsAt,100+DEFAULT_TRIAL_DAYS*86400000); });
test('an expired used trial cannot restart, including a zero timestamp', async()=>{ await adminDb.doc('subscriptions/alice').set({userId:'alice',status:'TRIALING',trialUsedAt:0,trialEndsAt:2}); await assert.rejects(()=>startTrial('alice',3), /TRIAL_ALREADY_USED/); const entitlement=await getEntitlements('alice',3); assert.equal(entitlement.effectivePlan,'FREE'); assert.equal(entitlement.trialEligible,false); });
test('manual assignment validates input and stores only MANUAL provider', async()=>{ const active=await assignManualSubscription('bob','PREMIUM','ACTIVE',1000,100); assert.equal(active.isPremium,true); assert.equal((await adminDb.doc('subscriptions/bob').get()).data().provider,'MANUAL'); await assert.rejects(()=>assignManualSubscription('bad uid','PREMIUM','ACTIVE',1000,100)); await assert.rejects(()=>assignManualSubscription('bob','PREMIUM','TRIALING',1000,100)); await assert.rejects(()=>assignManualSubscription('bob','PREMIUM','ACTIVE',99,100)); });
