import { normalizeRate, ReaderTtsAdapter, ReaderTtsCallbacks, ReaderTtsCapabilities, ReaderTtsError, ReaderTtsRequest, ReaderTtsVoice, selectPreferredVoice } from './types';
export class WebSpeechTtsAdapter implements ReaderTtsAdapter {
  private operation = 0; private rate = 1;
  private api() { return typeof window === 'undefined' ? undefined : window.speechSynthesis; }
  isSupported() { return Boolean(this.api() && typeof SpeechSynthesisUtterance !== 'undefined'); }
  getCapabilities(): ReaderTtsCapabilities { const available = this.isSupported(); return { ttsAvailable: available, boundaryEventsSupported: available, pauseResumeSupported: available, voicesAvailable: Boolean(this.api()?.getVoices().length) }; }
  async getVoices(): Promise<ReaderTtsVoice[]> { const api = this.api(); if (!api) return []; const map = () => api.getVoices().map(v => ({ id: v.voiceURI, name: v.name, language: v.lang, localService: v.localService, default: v.default })); const voices = map(); if (voices.length) return voices; return new Promise(resolve => { const done = () => { api.removeEventListener('voiceschanged', done); resolve(map()); }; api.addEventListener('voiceschanged', done, { once: true }); }); }
  setRate(rate: number) { this.rate = normalizeRate(rate); return this.rate; }
  speak(request: ReaderTtsRequest, callbacks: ReaderTtsCallbacks = {}) { const api = this.api(); if (!this.isSupported() || !api) { callbacks.onError?.({ code: 'not-supported', message: 'Speech synthesis is unavailable.' }); return; } const op = ++this.operation; api.cancel(); const utterance = new SpeechSynthesisUtterance(request.text); utterance.lang = request.language || 'en-US'; utterance.rate = this.setRate(request.rate ?? this.rate); void this.getVoices().then(voices => { if (op !== this.operation) return; const selected = selectPreferredVoice(voices, request.preferredVoiceId); if (selected) { const native = api.getVoices().find(v => v.voiceURI === selected.id); if (native) utterance.voice = native; } utterance.onstart = () => { if (op === this.operation) callbacks.onStart?.(); }; utterance.onboundary = event => { if (op === this.operation && Number.isInteger(event.charIndex)) callbacks.onBoundary?.({ charIndex: event.charIndex, charLength: Number(event.charLength) || undefined, name: event.name || undefined }); }; utterance.onpause = () => { if (op === this.operation) callbacks.onPause?.(); }; utterance.onresume = () => { if (op === this.operation) callbacks.onResume?.(); }; utterance.onend = () => { if (op === this.operation) callbacks.onEnd?.(); }; utterance.onerror = event => { if (op === this.operation) { const error: ReaderTtsError = { code: event.error === 'canceled' ? 'canceled' : 'synthesis-failed', message: event.error || 'Speech synthesis failed.' }; callbacks.onError?.(error); } }; api.speak(utterance); }); }
  pause() { this.api()?.pause(); } resume() { this.api()?.resume(); } stop() { this.operation += 1; this.api()?.cancel(); }
}
