import React, { useState } from 'react';
import { ArrowRight, CheckCircle, Volume2, XCircle } from 'lucide-react';
import { QuizResult, ReviewGrade, VocabularyWord } from '../types';
import { useReviewSession } from '../hooks/useReviewSession';

interface QuizEngineProps { words: VocabularyWord[]; onComplete: (result: QuizResult) => void; onExit: () => void; }
const grades: Array<[ReviewGrade, string]> = [['AGAIN', 'Tekrar'], ['HARD', 'Zor'], ['GOOD', 'İyi'], ['EASY', 'Kolay']];
const ttsSupported = () => typeof window !== 'undefined' && 'speechSynthesis' in window && typeof SpeechSynthesisUtterance !== 'undefined';

const QuizEngine: React.FC<QuizEngineProps> = ({ words, onComplete, onExit }) => {
  const session = useReviewSession(words, { size: Math.min(10, Math.max(5, words.length)), listening: ttsSupported() });
  const [input, setInput] = useState('');
  const question = session.currentQuestion;
  if (session.status === 'READY') return <div className="p-8 text-center">Tekrar için kelime bulunamadı.</div>;
  if (session.status === 'COMPLETE') return <div className="max-w-xl mx-auto rounded-3xl bg-white p-8 text-center shadow-xl dark:bg-gray-800"><CheckCircle className="mx-auto mb-4 text-green-600" size={48} /><h2 className="text-2xl font-black">Oturum tamamlandı</h2><p className="mt-3">{session.completed} kelime · {session.correct} doğru · {session.wrong} yanlış</p><p className="text-sm text-gray-500">Başarı: %{session.completed ? Math.round(session.correct * 100 / session.completed) : 0}</p><button onClick={() => onComplete({ score: session.correct, total: session.questions.length, wrongWordIds: [] })} className="mt-6 rounded-xl bg-brand-600 px-5 py-3 font-bold text-white">Deftere dön</button></div>;
  if (!question) return null;
  const replay = () => { if (!ttsSupported()) return; const utterance = new SpeechSynthesisUtterance(question.wordReference.word); utterance.lang = 'en-US'; window.speechSynthesis.speak(utterance); };
  const answer = (value: string) => { session.answerQuestion(value); setInput(value); };
  return <div className="max-w-xl mx-auto overflow-hidden rounded-3xl border bg-white shadow-2xl dark:bg-gray-800"><div className="h-2 bg-gray-100"><div className="h-full bg-brand-500" style={{ width: `${session.questions.length ? session.completed * 100 / session.questions.length : 0}%` }} /></div><div className="p-8"><div className="mb-6 flex justify-between text-xs font-black uppercase text-gray-400"><span>Soru {session.completed + 1}/{session.questions.length}</span><button onClick={onExit}>Çıkış</button></div><h2 className="mb-7 text-center text-2xl font-black dark:text-white">{question.question}</h2>{question.type === 'LISTEN' && <button aria-label="Kelimeyi tekrar dinle" onClick={replay} className="mx-auto mb-6 flex rounded-2xl bg-brand-100 p-6 text-brand-600"><Volume2 size={34} /></button>}{question.type === 'WRITE' ? <div className="space-y-3"><input aria-label="Cevabınızı yazın" value={input} disabled={session.status !== 'QUESTION'} onChange={event => setInput(event.target.value)} onKeyDown={event => event.key === 'Enter' && answer(input)} className="w-full rounded-xl border p-4 text-center text-lg dark:bg-gray-900"/><button disabled={!input || session.status !== 'QUESTION'} onClick={() => answer(input)} className="w-full rounded-xl bg-brand-600 p-4 font-bold text-white disabled:opacity-50">Kontrol Et</button></div> : <div className="space-y-3">{question.options?.map(option => <button key={option} disabled={session.status !== 'QUESTION'} onClick={() => answer(option)} className="w-full rounded-xl border p-4 text-left font-bold dark:border-gray-700">{option}</button>)}</div>}{session.status === 'ANSWERED' && session.answer && <div aria-live="polite" className="mt-7 rounded-2xl bg-gray-50 p-5 dark:bg-gray-900"><div className={`flex items-center gap-2 font-black ${session.answer.correct ? 'text-green-600' : 'text-red-600'}`}>{session.answer.correct ? <CheckCircle /> : <XCircle />}{session.answer.correct ? 'Doğru!' : `Doğru cevap: ${session.answer.expectedAnswer}`}</div><p className="mt-2 text-sm text-gray-500">{question.wordReference.word} — {question.wordReference.translation}</p><div className="mt-4 grid grid-cols-2 gap-2">{grades.map(([grade, label]) => <button key={grade} onClick={() => void session.submitGrade(grade)} className="rounded-xl bg-brand-600 p-3 font-bold text-white">{label}</button>)}</div></div>}{session.status === 'ERROR' && <div role="alert" className="mt-5 text-center text-red-600">{session.error}<button onClick={() => void session.retry(session.answer?.suggestedGrade || 'AGAIN')} className="ml-3 underline">Yeniden dene</button></div>}</div></div>;
};
export default QuizEngine;
