import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PreparedReaderToken } from '../services/readerLanguageData';
import { buildSpeechSegmentFromToken, findNextSentenceStartToken, findPreviousSentenceStartToken, findSentenceStartToken, resolveSegmentCharIndex } from '../services/tts/tokenSync';
import { ReaderTtsAdapter, ReaderTtsStatus, ReaderTtsVoice, normalizeRate } from '../services/tts/types';
import { createReaderTtsAdapter } from '../services/tts/native/nativeTtsFactory';

export const useReaderTts = (text: string, tokens: PreparedReaderToken[], injected?: ReaderTtsAdapter) => {
  const adapter = useMemo(() => injected || createReaderTtsAdapter(), [injected]); const session = useRef(0); const [status, setStatus] = useState<ReaderTtsStatus>('IDLE'); const [rate, setRateState] = useState(1); const [voice, setVoice] = useState<ReaderTtsVoice>(); const [voices, setVoices] = useState<ReaderTtsVoice[]>([]); const [activeTokenIndex, setActiveTokenIndex] = useState<number>(); const [activeSentenceId, setActiveSentenceId] = useState<string>(); const [followEnabled, setFollowEnabled] = useState(true); const capabilities = adapter.getCapabilities();
  useEffect(() => { void adapter.getVoices().then(setVoices); return () => { session.current += 1; adapter.stop(); }; }, [adapter]);
  useEffect(() => { session.current += 1; adapter.stop(); setStatus('IDLE'); setActiveTokenIndex(undefined); setActiveSentenceId(undefined); }, [adapter, text, tokens]);
  const startFromToken = useCallback((index = activeTokenIndex ?? tokens.find(t => t.isWord)?.index) => { if (index === undefined) return; const segment = buildSpeechSegmentFromToken(text, tokens, index); if (!segment) return; const id = ++session.current; adapter.speak({ text: segment.speechText, rate, language: 'en-US', preferredVoiceId: voice?.id }, { onStart: () => { if (id === session.current) setStatus('SPEAKING'); }, onBoundary: event => { if (id !== session.current || !capabilities.boundaryEventsSupported) return; const token = resolveSegmentCharIndex(segment, tokens, event.charIndex); if (token) { setActiveTokenIndex(previous => previous === token.index ? previous : token.index); setActiveSentenceId(previous => previous === token.sentenceId ? previous : token.sentenceId); } }, onPause: () => { if (id === session.current) setStatus('PAUSED'); }, onResume: () => { if (id === session.current) setStatus('SPEAKING'); }, onEnd: () => { if (id === session.current) setStatus('IDLE'); }, onError: () => { if (id === session.current) setStatus('ERROR'); } }); }, [activeTokenIndex, adapter, capabilities.boundaryEventsSupported, rate, text, tokens, voice?.id]);
  const stop = useCallback(() => { session.current += 1; adapter.stop(); setStatus('IDLE'); }, [adapter]);
  const pause = useCallback(() => { adapter.pause(); setStatus('PAUSED'); }, [adapter]); const resume = useCallback(() => { if (capabilities.pauseResumeSupported) { adapter.resume(); setStatus('SPEAKING'); } else startFromToken(); }, [adapter, capabilities.pauseResumeSupported, startFromToken]);
  const setRate = useCallback((value: number) => { const next = normalizeRate(value); setRateState(next); if (status === 'SPEAKING') { stop(); setTimeout(() => startFromToken(), 0); } }, [startFromToken, status, stop]);
  const sentence = (resolver: (values: PreparedReaderToken[], index: number) => PreparedReaderToken | null) => { if (activeTokenIndex === undefined) return; const token = resolver(tokens, activeTokenIndex); if (token) startFromToken(token.index); };
  return { supported: capabilities.ttsAvailable, synchronizationSupported: capabilities.boundaryEventsSupported, status, speaking: status === 'SPEAKING', paused: status === 'PAUSED', rate, voice, voices, setVoice, activeTokenIndex, activeSentenceId, followEnabled, setFollowEnabled, start: () => startFromToken(), startFromToken, pause, resume, stop, setRate, repeatCurrentSentence: () => activeSentenceId && startFromToken(findSentenceStartToken(tokens, activeSentenceId)?.index), previousSentence: () => sentence(findPreviousSentenceStartToken), nextSentence: () => sentence(findNextSentenceStartToken) };
};
